### ISSUE TITLE
Baidu Netdisk link provided is invalid

### ISSUE THREAD

**Issue by Neko-zxx** [Herbert-Gao/Driving-Style-Analysis#1]
Hello, the Baidu Netdisk link provided is invalid. Could you please update the link? Thank you very much!

**Comment by Herbert-Gao** [comment]
hi, I've noticed the problem and prepare to release version 2.0 in one week.
Anyway, I'm glad that you are interested in this project. Please check it after few days.

---Original---
From: ***@***.***&gt;
Date: Fri, Mar 4, 2022 21:06 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [Herbert-Gao/Driving-Style-Analysis] Baidu Netdisk link provided isinvalid (Issue #1)




 
Hello, the Baidu Netdisk link provided is invalid. Could you please update the link? Thank you very much!

**Comment by Herbert-Gao** [comment]
Version 1.0 Data link has updated. But it has to be mentioned that Version 1.0 only proves that Wang's work goes well.
